---
#
# Copyright 2014 Major Hayden
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

  - name: 3.1 Restrict Core Dumps to Protected Directory (Scored)
    file: path=/var/cores owner=root group=root mode=700 state=directory
    shell: coreadm
    shell: coreadm -g /var/cores/core_%n_%f_%u_%g_%t_%p
    shell: coreadm -e log
    shell: coreadm -e global
    shell: coreadm -e global-setid
    shell: coreadm -d process
    shell: coreadm -d proc-setid
    tags:
      - scored
      - section3.1

  - name: 3.2 Enable Stack Protection (Scored)
    lineinfile: >
      dest=/etc/system
      state=present
      line="set noexec_user_stack=1"
      backup=yes
    lineinfile: >
      dest=/etc/system
      state=present
      line="set noexec_user_stack_log=1"
      backup=yes
    tags:
      - scored
      - section3.2

  - name: 3.3 Enable Strong TCP Sequence Number Generation (Scored)
    lineinfile: >
      dest=/etc/default/inetinit
      state=present
      regexp="^TCP_STRONG_ISS="
      line="TCP_STRONG_ISS=2"
    tags:
      - scored
      - section3.3

  - name: 3.4 Modify Network Parameters
    tags:
      - section3.4

  - name: 3.4.1 Disable Source Packet Forwarding (Scored)
    lineinfile: line="ndd -set /dev/ip ip_forward_src_routed 0"
    when: globalzone or exclusive_ip_stack
    tags:
      - scored
      - section3.4
      - section3.4.1

  - name: 3.4.2 Disable Broadcast Packet Forwarding (Scored)
    lineinfile: line="ndd -set /dev/ip ip_forward_directed_broadcasts 0"
    when: globalzone or exclusive_ip_stack
    tags:
      - scored
      - section3.4
      - section3.4.2

  - name: 3.4.3 Disable Response to ICMP Timestamp Requests (Scored)
    lineinfile: line="ndd -set /dev/ip ip_respond_to_timestamp 0"
    when: globalzone or exclusive_ip_stack
    tags:
      - scored
      - section3.4
      - section3.4.3

  - name: 3.4.4 Disable Response to ICMP Broadcast Timestamp Requests (Scored)
    lineinfile: line="ndd -set /dev/ip ip_respond_to_timestamp_broadcast 0"
    when: globalzone or exclusive_ip_stack
    tags:
      - scored
      - section3.4
      - section3.4.4

  - name: 3.4.5 Disable Response to ICMP Netmask Requests (Scored)
    lineinfile: line="ndd -set /dev/ip ip_respond_to_address_mask_broadcast 0"
    when: globalzone or exclusive_ip_stack
    tags:
      - scored
      - section3.4
      - section3.4.5

  - name: 3.4.6 Disable ICMPv6 Redirect Messages (Scored)
    lineinfile: line="ndd -set /dev/ip ip6_send_redirects 0"
    when: globalzone or exclusive_ip_stack
    tags:
      - scored
      - section3.4
      - section3.4.6

  - name: 3.4.7 Disable Response to Broadcast ICMPv4 Echo Request (Scored)
    lineinfile: line="ndd -set /dev/ip ip_respond_to_echo_broadcast 0"
    when: globalzone or exclusive_ip_stack
    tags:
      - scored
      - section3.4
      - section3.4.7

  - name: 3.4.8 Disable Response to Multicast Echo Request (Scored)
    lineinfile: line="ndd -set /dev/ip ip_respond_to_echo_multicast 0"
    when: globalzone or exclusive_ip_stack
    tags:
      - scored
      - section3.4
      - section3.4.8

  - name: 3.4.9 Set Interval for Scanning IRE_CACHE (Scored)
    lineinfile: line="ndd -set /dev/ip ip_ire_arp_interval 60000"
    when: globalzone or exclusive_ip_stack
    tags:
      - scored
      - section3.4
      - section3.4.9

  - name: 3.4.10 Ignore ICMP Redirect Messages (Scored)
    lineinfile: line="ndd -set /dev/ip ip_ignore_redirect 1
    lineinfile: line="ndd -set /dev/ip ip6_ignore_redirect 1
    when: globalzone or exclusive_ip_stack
    tags:
      - scored
      - section3.4
      - section3.4.10

  - name: 3.4.11 Set Strict Multihoming (Scored)
    lineinfile: line="ndd -set /dev/ip ip_strict_dst_multihoming 1"
    lineinfile: line="ndd -set /dev/ip ip6_strict_dst_multihoming 1"
    when: globalzone or exclusive_ip_stack
    tags:
      - scored
      - section3.4
      - section3.4.11

  - name: 3.4.12 Disable ICMPv4 Redirect Messages (Scored)
    lineinfile: line="ndd -set /dev/ip ip_send_redirects 0"
    when: globalzone or exclusive_ip_stack
    tags:
      - scored
      - section3.4
      - section3.4.12

  - name: 3.4.13 Set ARP Cleanup Interval (Scored)
    lineinfile: line="ndd -set /dev/arp arp_cleanup_interval 60000
    when: globalzone or exclusive_ip_stack
    tags:
      - scored
      - section3.4
      - section3.4.13

  - name: 3.4.14 Disable TCP Reverse IP Routing (Scored)
    lineinfile: line="ndd -set /dev/tcp tcp_rev_src_routes 0"
    when: globalzone or exclusive_ip_stack
    tags:
      - scored
      - section3.4
      - section3.4.14

  - name: 3.4.15 Set Maximum Number of Half-open TCP Connections (Scored)
    lineinfile: line="ndd -set /dev/tcp tcp_conn_req_max_q0 4096"
    XXX: only increase
    when: globalzone or exclusive_ip_stack
    tags:
      - scored
      - section3.4
      - section3.4.15

  - name: 3.4.16 Set Maximum Number of Incoming Connections (Scored)
    lineinfile: line="ndd -set /dev/tcp tcp_conn_req_max_q 1024"
    XXX: only increase
    when: globalzone or exclusive_ip_stack
    tags:
      - scored
      - section3.4
      - section3.4.16

  - name: 3.4.17 Lock down dtspcd (Scored)
    lineinfile: line="ndd -set /dev/tcp tcp_extra_priv_ports_add 6112"
    when: globalzone or exclusive_ip_stack
    tags:
      - scored
      - section3.4
      - section3.4.17

  - name: 3.5 Disable Network Routing
    shell: routeadm -d ipv4-forwarding -d ipv6-forwarding
    shell: routeadm -d ipv4-routing -d ipv6-routing
    shell: routeadm -u
    when: globalzone or exclusive_ip_stack
    tags:
      - scored
      - section3.5
