---
#
# Copyright 2014 Major Hayden
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

  - name: 2.1 Establish a Secure Baseline (Scored)
    debug: netservices limited
    tags:
      - scored
      - section2.1

  - name: 2.2 Disable Unnecessary Local Services
    tags:
      - section2.2

  - name: 2.2.1 Disable Local CDE ToolTalk Database Server (Scored)
    service: >
      name=svc:/network/rpc/cde-ttdbserver:tcp
      state=stopped
    tags:
      - scored
      - section2.2
      - section2.2.1

  - name: 2.2.2 Disable Local CDE Calendar Manager (Scored)
    service: >
      name=svc:/network/rpc/cde-calendar-manager:default
      state=stopped
    tags:
      - scored
      - section2.2
      - section2.2.2

  - name: 2.2.3 Disable Local Graphical Login Environment (Scored)
    service: >
      name=svc:/application/graphical-login/cde-login
      state=stopped
    service: >
      name=svc:/application/gdm2-login
      state=stopped
    tags:
      - scored
      - section2.2
      - section2.2.3

  - name: 2.2.4 Disable Local sendmail Service (Scored)
    service: >
      name=svc:/network/smtp:sendmail
      state=stopped
    tags:
      - scored
      - section2.2
      - section2.2.4

  - name: 2.2.5 Disable Local Web Console (Scored)
    service: >
      name=svc:/system/webconsole:console
      state=stopped
    tags:
      - scored
      - section2.2
      - section2.2.5

  - name: 2.2.6 Disable Local WBEM (Scored)
    service: >
      name=svc:/application/management/wbem
      state=stopped
    tags:
      - scored
      - section2.2
      - section2.2.6

  - name: 2.2.7 Disable Local BSD Print Protocol Adapter (Scored)
    service: >
      name=svc:/application/print/rfc1179
      state=stopped
    tags:
      - scored
      - section2.2
      - section2.2.7

  - name: 2.3 Disable Other Services
    tags:
      - section2.3

  - name: 2.3.1 Disable RPC Encryption Key (Scored)
    service: >
      name=svc:/network/rpc/keyserv
      state=stopped
    tags:
      - scored
      - section2.3
      - section2.3.1

  - name: 2.3.2 Disable NIS Server Daemons (Scored)
    service: name=svc:/network/nis/server state=stopped
    service: name=svc:/network/nis/passwd state=stopped
    service: name=svc:/network/nis/update state=stopped
    service: name=svc:/network/nis/xfr state=stopped
    tags:
      - scored
      - section2.3
      - section2.3.2

  - name: 2.3.3 Disable NIS Client Daemons (Scored)
    service: >
      name=svc:/network/nis/client
      state=stopped
    tags:
      - scored
      - section2.3
      - section2.3.3

  - name: 2.3.4 Disable NIS+ Daemons (Scored)
    service: >
      name=svc:/network/rpc/nisplus
      state=stopped
    tags:
      - scored
      - section2.3
      - section2.3.4

  - name: 2.3.5 Disable LDAP Cache Manager (check if LDAP is configured) (Scored)
    shell: /usr/sbin/ldapclient list
    register: ldap_configured
    tags:
      - scored
      - section2.3
      - section2.3.5

  - name: 2.3.5 Disable LDAP Cache Manager (Scored)
    service: >
      name=svc:/network/ldap/client
      state=stopped
    when: ldap_configured|failed
    tags:
      - scored
      - section2.3
      - section2.3.5

  - name: 2.3.6 Disable Kerberos TGT Expiration Warning (Scored)
    service: >
      name=svc:/network/security/ktkt_warn
      state=stopped
    tags:
      - scored
      - section2.3
      - section2.3.6

  - name: 2.3.7 Disable Generic Security Services (GSS) Daemons (Scored)
    service: >
      name=svc:/network/rpc/gss
      state=stopped
    tags:
      - scored
      - section2.3
      - section2.3.7

  - name: 2.3.8 Disable Volume Manager (Scored)
    service: >
      name=svc:/system/filesystem/volfs
      state=stopped
    service: >
      name=svc:/network/rpc/smserver
      state=stopped
    tags:
      - scored
      - section2.3
      - section2.3.8

  - name: 2.3.9 Disable Samba Support (Scored)
    service: >
      name=svc:/network/samba
      state=stopped
    tags:
      - scored
      - section2.3
      - section2.3.9

  - name: 2.3.10 Disable automount Daemon (Scored)
    service: >
      name=svc:/system/filesystem/autofs
      state=stopped
    tags:
      - scored
      - section2.3
      - section2.3.10

  - name: 2.3.11 Disable Apache Services (Scored)
    service: >
      name=svc:/network/http:apache2
      state=stopped
    tags:
      - scored
      - section2.3
      - section2.3.11

  - name: 2.3.12 Disable Solaris Volume Manager Services (Scored)
    service: >
      name=svc:/system/metainit
      state=stopped
    when: globalzone
    service: >
      name=svc:/system/mdmonitor
      state=stopped
    when: globalzone
    tags:
      - scored
      - section2.3
      - section2.3.12

  - name: 2.3.13 Disable Solaris Volume Manager GUI (Scored)
    service: name=svc:/network/rpc/mdcomm state=stopped
    when: globalzone
    service: name=svc:/network/rpc/meta state=stopped
    when: globalzone
    service: name=svc:/network/rpc/metamed state=stopped
    when: globalzone
    service: name=svc:/network/rpc/metamh state=stopped
    when: globalzone
    tags:
      - scored
      - section2.3
      - section2.3.13

  - name: 2.3.14 Disable Local RPC Port Mapping Service (Scored)
    service: >
      name=svc:/network/rpc/bind
      state=stopped
    debug: May use tcpwrapper
    debug: disable only when not needed
    tags:
      - scored
      - section2.3
      - section2.3.14

  - name: 2.4 Configure TCP Wrappers
    tags:
      - scored
      - section2.4
      
