---
#
# Copyright 2014 Major Hayden
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

  - name: 4.1 Enable inetd Connection Logging (Scored)
    shell: inetadm -M tcp_trace=true
    shell: svcadm refresh svc:/network/inetd
    XXX: audit svcprop -p defaults/tcp_trace svc:/network/inetd
    tags:
      - scored
      - section4.1

  - name: 4.2 Enable FTP daemon Logging (Scored)
    shell: inetadm -m svc:/network/ftp exec="/usr/sbin/in.ftpd -a -l -d"
    XXX: audit svcprop -p inetd_start/exec svc:/network/ftp "/usr/sbin/in.ftpd -a -l -d"
    tags:
      - scored
      - section4.2

  - name: 4.3 Enable Debug Level Daemon Logging (Scored)
    - file: path=/var/log/connlog owner=root group=root mode=600 state=file
    - shell: logadm -w connlog -C 13 -a 'pkill -HUP syslogd' /var/log/connlog
    - lineinfile: dest=/etc/syslog.conf line="daemon.debug\t\t\t/var/log/connlog" 
      register: syslog
    - shell: svcadm refresh svc:/system/system-log
      when: syslog.changed
    tags:
      - scored
      - section4.3

  - name: 4.4 Capture syslog AUTH Messages (Scored)
    - file: path=/var/log/authlog owner=root group=sys mode=600 state=file
    - shell: logadm -w authlog -C 13 -a 'pkill -HUP syslogd' /var/log/authlog
    - lineinfile: dest=/etc/syslog.conf line="auth.info\t\t\t/var/log/authlog" 
      register: syslog
    - shell: svcadm refresh svc:/system/system-log
      when: syslog.changed
    tags:
      - scored
      - section4.4

  - name: 4.5 Enable Login Records (Scored)
    - file: path=/var/adm/loginlog owner=root group=sys mode=600 state=file
    - shell: logadm -w authlog -C 13 /var/adm/loginlog
    tags:
      - scored
      - section4.5

  - name: 4.6 Capture All Failed Login Attempts (Scored)
    - lineinfile: dest=/etc/default/login regex="^SYSLOG_FAILED_LOGINS=" insertafter="^#SYSLOG_FAILED_LOGINS=" line="SYSLOG_FAILED_LOGINS=0"
      register: login
    - shell: pkgchk -f -n -p /etc/default/login
      when: login.changed
    tags:
      - scored
      - section4.6

  - name: 4.7 Enable cron Logging (Scored)
    - file: path=/var/cron/log owner=root group=root mode=go-rwx
    - lineinfile: dest=/etc/default/cron regex="^CRONLOG=" intertafter="^#CRONLOG=" line="CRONLOG=YES"
      register: cron
    - shell: pkgchk -f -n -p /etc/default/cron
      when: cron.changed
    tags:
      - scored
      - section4.7

  - name: 4.8 Enable System Accounting (Scored)
    - service: >
        name=svc:/system/sar
        state=started
    - cron: user=sys minute="0,20,40" job="/usr/lib/sa/sa1" state=present
    - cron: user=sys minute="45" hour="23" job="/usr/lib/sa/sa2 -s 0:00 -e 23:59 -i 1200 -A" state=present
    - file: path={{ item }} owner=sys group=sys mode=go-wx
      with_fileglob: /var/adm/sa/*

  - name: 4.9 Kernel Level Auditing (Scored)
    XXX: TBD
